name: Pull Request

on: pull_request

jobs:
  test_env_passing:
    name: Test Env Passing
    timeout-minutes: 5
    runs-on: windows-latest
    env:
      TEST_DATA: I can pass things via env!
    steps:
    - uses: ${{ github.action_path }}/test-env